export type MotivationalQuote = {
  content: string;
  author: string;
  source: string;
};

export const motivationalQuotes: MotivationalQuote[] = [
  // ---- 中国古典名句 ----
  { content: "学而不思则罔，思而不学则殆。", author: "孔子", source: "论语" },
  { content: "温故而知新，可以为师矣。", author: "孔子", source: "论语" },
  { content: "三人行，必有我师焉。", author: "孔子", source: "论语" },
  { content: "知之为知之，不知为不知，是知也。", author: "孔子", source: "论语" },
  { content: "学而时习之，不亦说乎。", author: "孔子", source: "论语" },
  { content: "敏而好学，不耻下问。", author: "孔子", source: "论语" },
  { content: "己所不欲，勿施于人。", author: "孔子", source: "论语" },
  { content: "择其善者而从之，其不善者而改之。", author: "孔子", source: "论语" },
  { content: "工欲善其事，必先利其器。", author: "孔子", source: "论语" },
  { content: "学而不厌，诲人不倦。", author: "孔子", source: "论语" },
  { content: "千里之行，始于足下。", author: "老子", source: "道德经" },
  { content: "知人者智，自知者明。", author: "老子", source: "道德经" },
  { content: "胜人者有力，自胜者强。", author: "老子", source: "道德经" },
  { content: "天下难事，必作于易；天下大事，必作于细。", author: "老子", source: "道德经" },
  { content: "合抱之木，生于毫末。", author: "老子", source: "道德经" },
  { content: "宝剑锋从磨砺出，梅花香自苦寒来。", author: "朱熹", source: "警世贤文" },
  { content: "业精于勤，荒于嬉；行成于思，毁于随。", author: "韩愈", source: "进学解" },
  { content: "书山有路勤为径，学海无涯苦作舟。", author: "韩愈", source: "增广贤文" },
  { content: "天生我材必有用。", author: "李白", source: "将进酒" },
  { content: "长风破浪会有时，直挂云帆济沧海。", author: "李白", source: "行路难" },
  { content: "天行健，君子以自强不息。", author: "易经", source: "周易" },
  { content: "地势坤，君子以厚德载物。", author: "易经", source: "周易" },
  { content: "不积跬步，无以至千里。", author: "荀子", source: "劝学" },
  { content: "锲而不舍，金石可镂。", author: "荀子", source: "劝学" },
  { content: "青，取之于蓝，而青于蓝。", author: "荀子", source: "劝学" },
  { content: "学不可以已。", author: "荀子", source: "劝学" },
  { content: "路漫漫其修远兮，吾将上下而求索。", author: "屈原", source: "离骚" },
  { content: "少壮不努力，老大徒伤悲。", author: "汉乐府", source: "长歌行" },
  { content: "莫等闲，白了少年头，空悲切。", author: "岳飞", source: "满江红" },
  { content: "有志者，事竟成。", author: "范晔", source: "后汉书" },
  { content: "世上无难事，只怕有心人。", author: "民间谚语", source: "增广贤文" },
  { content: "一寸光阴一寸金，寸金难买寸光阴。", author: "民间谚语", source: "增广贤文" },
  { content: "黑发不知勤学早，白首方悔读书迟。", author: "颜真卿", source: "劝学" },
  { content: "读书破万卷，下笔如有神。", author: "杜甫", source: "奉赠韦左丞丈二十二韵" },
  { content: "博学之，审问之，慎思之，明辨之，笃行之。", author: "礼记", source: "中庸" },
  { content: "玉不琢，不成器；人不学，不知道。", author: "礼记", source: "学记" },
  { content: "学然后知不足，教然后知困。", author: "礼记", source: "学记" },
  { content: "古之立大事者，不惟有超世之才，亦必有坚忍不拔之志。", author: "苏轼", source: "晁错论" },
  { content: "纸上得来终觉浅，绝知此事要躬行。", author: "陆游", source: "冬夜读书示子聿" },
  { content: "问渠那得清如许，为有源头活水来。", author: "朱熹", source: "观书有感" },
  { content: "千淘万漉虽辛苦，吹尽狂沙始到金。", author: "刘禹锡", source: "浪淘沙" },
  { content: "山重水复疑无路，柳暗花明又一村。", author: "陆游", source: "游山西村" },
  { content: "不登高山，不知天之高也。", author: "荀子", source: "劝学" },
  { content: "知而好学，然后能才。", author: "荀子", source: "劝学" },
  { content: "学贵有疑，小疑则小进，大疑则大进。", author: "陈献章", source: "语录" },
  { content: "立志宜思真品格，读书须尽苦功夫。", author: "阮元", source: "坐右铭" },
  { content: "非淡泊无以明志，非宁静无以致远。", author: "诸葛亮", source: "诫子书" },
  { content: "夫学须静也，才须学也。", author: "诸葛亮", source: "诫子书" },
  { content: "志当存高远。", author: "诸葛亮", source: "诫外生书" },
  { content: "学须静，才须学。非学无以广才，非志无以成学。", author: "诸葛亮", source: "诫子书" },

  // ---- 近现代名言 ----
  { content: "为中华之崛起而读书。", author: "周恩来", source: "少年时期" },
  { content: "活到老，学到老。", author: "毛泽东", source: "语录" },
  { content: "书是人类进步的阶梯。", author: "高尔基", source: "语录" },
  { content: "天才就是百分之一的灵感加上百分之九十九的汗水。", author: "爱迪生", source: "语录" },
  { content: "知识就是力量。", author: "培根", source: "沉思录" },
  { content: "我思故我在。", author: "笛卡尔", source: "方法论" },
  { content: "读一切好书，就是和许多高尚的人谈话。", author: "笛卡尔", source: "语录" },
  { content: "时间就是生命。", author: "鲁迅", source: "语录" },
  { content: "哪里有天才，我是把别人喝咖啡的功夫都用在工作上的。", author: "鲁迅", source: "语录" },
  { content: "横眉冷对千夫指，俯首甘为孺子牛。", author: "鲁迅", source: "自嘲" },
  { content: "世上本没有路，走的人多了，也便成了路。", author: "鲁迅", source: "故乡" },
  { content: "成功之花，人们往往惊羡它现时的明艳，然而当初，它的芽儿却浸透了奋斗的泪泉。", author: "冰心", source: "繁星" },

  // ---- 西方经典 ----
  { content: "The unexamined life is not worth living.", author: "Socrates", source: "Plato's Apology" },
  { content: "The only true wisdom is in knowing you know nothing.", author: "Socrates", source: "Quotes" },
  { content: "Wonder is the beginning of wisdom.", author: "Socrates", source: "Quotes" },
  { content: "Be kind, for everyone you meet is fighting a hard battle.", author: "Plato", source: "Quotes" },
  { content: "Necessity is the mother of invention.", author: "Plato", source: "Republic" },
  { content: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle", source: "Nicomachean Ethics" },
  { content: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle", source: "Quotes" },
  { content: "It is the mark of an educated mind to be able to entertain a thought without accepting it.", author: "Aristotle", source: "Nicomachean Ethics" },
  { content: "Quality is not an act, it is a habit.", author: "Aristotle", source: "Quotes" },
  { content: "If I have seen further it is by standing on the shoulders of Giants.", author: "Isaac Newton", source: "Letter" },
  { content: "Truth is ever to be found in simplicity.", author: "Isaac Newton", source: "Quotes" },
  { content: "I have no special talents. I am only passionately curious.", author: "Albert Einstein", source: "Letter" },
  { content: "Logic will get you from A to B. Imagination will take you everywhere.", author: "Albert Einstein", source: "Quotes" },
  { content: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein", source: "Letter" },
  { content: "In the middle of difficulty lies opportunity.", author: "Albert Einstein", source: "Quotes" },
  { content: "The important thing is not to stop questioning.", author: "Albert Einstein", source: "Quotes" },
  { content: "Try not to become a man of success but rather try to become a man of value.", author: "Albert Einstein", source: "Quotes" },
  { content: "A person who never made a mistake never tried anything new.", author: "Albert Einstein", source: "Quotes" },
  { content: "The measure of intelligence is the ability of change.", author: "Albert Einstein", source: "Quotes" },
  { content: "Knowledge is power.", author: "Francis Bacon", source: "Meditations Sacrae" },
  { content: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela", source: "Speech" },
  { content: "It always seems impossible until it's done.", author: "Nelson Mandela", source: "Quotes" },
  { content: "I learned that courage was not the absence of fear, but the triumph over it.", author: "Nelson Mandela", source: "Autobiography" },
  { content: "Continuous effort, not strength or intelligence, is the key to unlocking our potential.", author: "Winston Churchill", source: "Quotes" },
  { content: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill", source: "Speech" },
  { content: "Never, never, never, never give up.", author: "Winston Churchill", source: "Speech" },
  { content: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt", source: "First Inaugural Address" },
  { content: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt", source: "Quotes" },
  { content: "A smooth sea never made a skilled sailor.", author: "Franklin D. Roosevelt", source: "Quotes" },
  { content: "The best way to predict the future is to create it.", author: "Abraham Lincoln", source: "Quotes" },
  { content: "Give me six hours to chop down a tree and I will spend the first four sharpening the axe.", author: "Abraham Lincoln", source: "Quotes" },
  { content: "The only way to do great work is to love what you do.", author: "Steve Jobs", source: "Stanford Commencement" },
  { content: "Stay hungry, stay foolish.", author: "Steve Jobs", source: "Stanford Commencement" },
  { content: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs", source: "Stanford Commencement" },
  { content: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs", source: "Quotes" },
  { content: "The people who are crazy enough to think they can change the world are the ones who do.", author: "Steve Jobs", source: "Apple Ad" },
  { content: "If you are born poor it's not your mistake, but if you die poor it's your mistake.", author: "Bill Gates", source: "Quotes" },
  { content: "Don't compare yourself with anyone in this world.", author: "Bill Gates", source: "Quotes" },
  { content: "Today is cruel, tomorrow is worse, but the day after tomorrow is beautiful.", author: "Jack Ma", source: "Speech" },
  { content: "Never give up. Today is hard, tomorrow will be worse, but the day after tomorrow will be sunshine.", author: "Jack Ma", source: "Speech" },
  { content: "Opportunity lies in the place where the complaints are.", author: "Jack Ma", source: "Speech" },

  // ---- 世界谚语 ----
  { content: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb", source: "Proverbs" },
  { content: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu", source: "Tao Te Ching" },
  { content: "Fall seven times, stand up eight.", author: "Japanese Proverb", source: "Proverbs" },
  { content: "Where there is a will, there is a way.", author: "English Proverb", source: "Proverbs" },
  { content: "Rome was not built in a day.", author: "English Proverb", source: "Proverbs" },
  { content: "Practice makes perfect.", author: "English Proverb", source: "Proverbs" },
  { content: "Fortune favors the bold.", author: "Virgil", source: "Aeneid" },
  { content: "Patience is bitter, but its fruit is sweet.", author: "Jean-Jacques Rousseau", source: "Emile" },
  { content: "Nothing is impossible. The word itself says 'I'm possible'.", author: "Audrey Hepburn", source: "Quotes" },
  { content: "Believe you can and you're halfway there.", author: "Theodore Roosevelt", source: "Quotes" },
  { content: "The harder you work, the luckier you get.", author: "Gary Player", source: "Quotes" },
  { content: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn", source: "Quotes" },
  { content: "Don't wish it were easier. Wish you were better.", author: "Jim Rohn", source: "Quotes" },
  { content: "Action expresses priorities.", author: "Mahatma Gandhi", source: "Quotes" },
  { content: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi", source: "Quotes" },
  { content: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi", source: "Quotes" },
  { content: "The secret of getting ahead is getting started.", author: "Mark Twain", source: "Quotes" },
  { content: "If opportunity doesn't knock, build a door.", author: "Milton Berle", source: "Quotes" },
  { content: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt", source: "Quotes" },
  { content: "When something is important enough, you do it even if the odds are not in your favor.", author: "Elon Musk", source: "Speech" },
  { content: "However difficult life may seem, there is always something you can do and succeed at.", author: "Stephen Hawking", source: "Speech" },
  { content: "Intelligence is the ability to adapt to change.", author: "Stephen Hawking", source: "Quotes" },
  { content: "Look up at the stars and not down at your feet.", author: "Stephen Hawking", source: "Quotes" },
  { content: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama", source: "Quotes" },
  { content: "The mind is everything. What you think you become.", author: "Buddha", source: "Quotes" },
  { content: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot", source: "Quotes" },
  { content: "Every expert was once a beginner.", author: "Helen Hayes", source: "Quotes" },
  { content: "What we think, we become.", author: "Buddha", source: "Quotes" },
  { content: "Courage is not having the strength to go on, it is going on when you don't have the strength.", author: "Theodore Roosevelt", source: "Quotes" },
  { content: "Education is not the filling of a pail, but the lighting of a fire.", author: "William Butler Yeats", source: "Quotes" },
  { content: "The first step is you have to say that you can.", author: "Will Smith", source: "Quotes" },
  { content: "When you talk, you are only repeating what you already know. But if you listen, you may learn something new.", author: "Dalai Lama", source: "Quotes" },
  { content: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford", source: "Quotes" },
  { content: "The best revenge is massive success.", author: "Frank Sinatra", source: "Quotes" },
];
